version: "2.4"
services:
  dtrack:
    image: "owasp/dependency-track"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "1337:8080"
    volumes:
      - "./dtrack:/data"
    environment:
      # The Dependency-Track container can be configured using any of the
      # available configuration properties defined in:
      # https://docs.dependencytrack.org/getting-started/configuration/
      # All properties are upper case with periods replaced by underscores.
      #
      # Database Properties
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://db:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_DRIVER_PATH=/extlib/postgresql-42.2.5.jar
      - ALPINE_DATABASE_USERNAME=postgres
      - ALPINE_DATABASE_PASSWORD=password
    # - ALPINE_DATABASE_POOL_ENABLED=true
    # - ALPINE_DATABASE_POOL_MAX_SIZE=10
    # - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=600000
    # - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000

  db:
    image: "postgres"
    restart: always
    healthcheck: # Used for waiting the db to be up and running
      test: ["CMD-SHELL", "pg_isready -U postgres -d gitea"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "54320:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: dtrack
